export const NIGERIAN_UNIVERSITIES = [
  "University of Lagos (UNILAG)",
  "University of Ibadan (UI)",
  "University of Nigeria, Nsukka (UNN)",
  "Obafemi Awolowo University (OAU)",
  "Ahmadu Bello University (ABU)",
  "University of Benin (UNIBEN)",
  "University of Ilorin (UNILORIN)",
  "Federal University Oye-Ekiti (FUOYE)",
  "Federal University of Technology, Akure (FUTA)",
  "Federal University of Technology, Minna (FUTMINNA)",
  "Federal University of Technology, Owerri (FUTO)",
  "Federal University of Agriculture, Abeokuta (FUNAAB)",
  "Lagos State University (LASU)",
  "Ladoke Akintola University of Technology (LAUTECH)",
  "Olabisi Onabanjo University (OOU)",
  "Tai Solarin University of Education (TASUED)",
  "Ekiti State University (EKSU)",
  "Kwara State University (KWASU)",
  "Covenant University",
  "Babcock University",
  "Afe Babalola University (ABUAD)",
  "Landmark University",
  "Nile University",
  "Baze University",
  "Pan-Atlantic University",
  "Bells University of Technology",
  "Redeemer's University",
  "Bowen University",
  "Caleb University",
  "Ajayi Crowther University",
  "Lead City University",
  "Elizade University",
  "Mcpherson University",
  "Joseph Ayo Babalola University (JABU)",
  "Chrisland University",
  "Samuel Adegboyega University",
  "Anchor University",
  "Summit University",
  "Al-Hikmah University",
  "Fountain University",
  "Oduduwa University",
  "University of Abuja (UNIABUJA)",
  "University of Jos (UNIJOS)",
  "University of Maiduguri (UNIMAID)",
  "University of Port Harcourt (UNIPORT)",
  "University of Uyo (UNIUYO)",
  "University of Calabar (UNICAL)",
  "Bayero University Kano (BUK)",
  "Nnamdi Azikiwe University (UNIZIK)",
  "Usmanu Danfodiyo University Sokoto (UDUS)",
  "Ambrose Alli University (AAU)",
  "Delta State University (DELSU)",
  "Rivers State University (RSU)",
  "Enugu State University of Science and Technology (ESUT)",
  "Ebonyi State University (EBSU)",
  "Abia State University (ABSU)",
  "Imo State University (IMSU)",
  "Benue State University (BSU)",
  "Kogi State University (KSU)",
  "Nasarawa State University (NSUK)",
  "Plateau State University (PLASU)",
  "Gombe State University (GSU)",
  "Bauchi State University (BASUG)",
  "Yobe State University (YSU)",
  "Borno State University (BOSU)",
  "Taraba State University (TASU)",
  "Adamawa State University (ADSU)",
  "Sokoto State University (SSU)",
  "Kano University of Science and Technology (KUST)",
  "Akwa Ibom State University (AKSU)",
  "Cross River University of Technology (CRUTECH)",
  "Niger Delta University (NDU)",
  "Federal University Dutse (FUD)",
  "Federal University Lokoja (FULOKOJA)",
  "Federal University Lafia (FULAFIA)",
  "Federal University Gashua (FUGA)",
  "Federal University Gusau (FUGUS)",
  "Federal University Kashere (FUK)",
  "Federal University Wukari (FUWUKARI)",
  "Federal University Birnin Kebbi (FUBK)",
  "Alex Ekwueme Federal University Ndufu-Alike (AE-FUNAI)",
  "Federal University Otueke (FUO)",
  "Federal University Dutsin-Ma (FUDMA)",
  "Michael Okpara University of Agriculture (MOUAU)",
  "Federal University of Agriculture, Makurdi (FUAM)",
  "Modibbo Adama University of Technology (MAUTECH)",
  "Federal University of Petroleum Resources Effurun (FUPRE)",
  "Nigeria Maritime University Okerenkoko",
  "American University of Nigeria (AUN)",
  "Skyline University Nigeria",
  "Dominion University",
  "KolaDaisi University",
  "Atiba University",
  "Westland University",
  "Precious Cornerstone University",
  "Air Force Institute of Technology",
  "Nigeria Police Academy Wudil",
];

export const DEPARTMENTS = [
  "Computer Science",
  "Electrical Engineering",
  "Mechanical Engineering",
  "Civil Engineering",
  "Medicine & Surgery",
  "Nursing",
  "Pharmacy",
  "Law",
  "Accounting",
  "Economics",
  "Biochemistry",
  "Business Administration",
  "Political Science",
  "Mass Communication",
  "Microbiology",
  "Philosophy",
  "English",
  "History",
  "Agriculture",
  "Geology",
  "Physics",
  "Mathematics",
  "Chemistry",
  "Sociology",
  "Psychology",
  "International Relations",
  "Banking & Finance",
  "Architecture",
  "Estate Management",
  "Urban & Regional Planning",
  "Quantity Surveying",
  "Building",
  "Marketing",
  "Public Administration",
  "Statistics",
  "Plant Biology",
  "Animal Biology",
  "Physiology",
  "Anatomy",
  "Medical Laboratory Science",
  "Radiography",
  "Optometry",
  "Dentistry",
  "Industrial Relations",
  "Human Resource Management",
  "Cooperative Economics",
  "Entrepreneurship",
  "Criminology",
  "Insurance",
];

export const LEVELS = ["100", "200", "300", "400", "500", "600", "700"];
export const SEMESTERS = ["Harmattan", "Rain"];
export const ACADEMIC_YEARS = [
  "2024/2025",
  "2023/2024",
  "2022/2023",
  "2021/2022",
  "2020/2021",
];
export const MATERIAL_TYPES = ["Test", "Exam", "CBT", "Assignment"];
